# Main Menu Configuration
main:
  - identifier: "lyrics"
    name: "Lyrics"
    url: "/lyrics/"
    weight: 20
  - identifier: posts # New unique identifier
    name: Posts # Or "Pronunciation", "Learn Language", etc.
    url: /posts/
    weight: 10 # Adjust weight to control order
  - identifier: "authors"
    name: "Authors"
    url: "/authors/" # Link to the list of all authors
    weight: 30
  - identifier: "tags"
    name: "Tags"
    url: "/tags/" # Link to the list of all tags
    weight: 40
  - identifier: Search
    name: Search
    url: /search/
    weight: 500
