# Site-wide parameters (apply regardless of theme, unless overridden)
description: A personal collection of lyrics, garba and discussions on pop culture.
author: Dr.Blank
homeInfoParams:
  Title: "Kalaa: Gujarati Art in Verse" # Explains and specifies focus
  Content: > # Use > for a nice multi-line block in YAML
    **Kalaa (કળા)** • **/kə.ɭɑː/** • _Gujarati: Art, Craft_<br><br>

    Welcome to my personal corner! This space is dedicated to exploring 'Kalaa' – the art –
    within Gujarati lyrical traditions. Discover curated lyrics (many Garba!), occasional film reviews, and musings on language, history, and culture through a Gujarati lens. Discover curated lyrics, delve into meanings, and share in the joy of expression."

socialIcons:
  - name: github
    url: https://github.com/Dr-Blank/Kalaa

ShowReadingTime: true
ShowShareButtons: true
ShowPostNavLinks: true
ShowBreadCrumbs: true
ShowCodeCopyButtons: true
ShowWordCount: false
ShowRssButtonInSectionTermList: true
ShowToc: true # Table of Contents
TocOpen: false
hideMeta: false # Ensure meta is generally shown
hideTaxonomies: false # Ensure taxonomies are shown in meta
fuseOpts:
  isCaseSensitive: false
  shouldSort: true
  location: 0
  distance: 1000
  threshold: 0.4
  minMatchCharLength: 0
  keys:
    - title
    - permalink
    - summary
    - content
label:
  icon: "/image.png"
  text: "Kalaa"

cover:
  linkFullImages: false # unnecessary
  responsiveImages: true
  # hidden: true
  # hiddenInList: true
  # hiddenInSingle: true
# editPost:
#   URL: "https://github.com/Dr-Blank/Kalaa/tree/main/content"
#   Text: "Suggest Changes" # edit text
#   appendFilePath: true # to append file path to Edit link

comments: true
