baseURL = "https://kala.drblank.dev/"   # IMPORTANT: Use your chosen subdomain
languageCode = "en-us"
title = "Kala | Dr. Blank's Art Corner"
theme = "PaperMod"


[params]
description = "A collection of pop culture musings"
author = "Dr. Blank"

# Enable search
[params.homeInfoParams]
Title = "Sangeet"
Content = "A personal collection of Gujarati lyrics, film thoughts, and cultural musings"

[[params.socialIcons]]
name = "github"
url = "https://github.com/dr-blank"

[menu]
[[menu.main]]
identifier = "lyrics"
name = "Lyrics"
url = "/lyrics/"
weight = 10
[[menu.main]]
identifier = "reviews"
name = "Film Reviews"
url = "/reviews/"
weight = 20
[[menu.main]]
identifier = "culture"
name = "Culture"
url = "/culture/"
weight = 30
